# This docker-compose file is used to run the project's published image
#
# Usage: docker-compose up [-d]
#
# See comment in docker-compose.dev.yml if you want to run for development.

version: '3.4'

networks:
  api:
    external:
      name: api.reaction.localhost
  auth:
    external:
      name: auth.reaction.localhost

services:
  web:
    image: reactioncommerce/example-storefront:release-v3.0.0
    env_file:
      - ./.env
    networks:
      api:
      auth:
    ports:
      - 4000:4000
